"""add column created_at and updated_at to series table

Revision ID: 2920bcbd973a
Revises: b756ee51c7a6
Create Date: 2024-03-16 23:47:57.643593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2920bcbd973a"
down_revision: Union[str, None] = "b756ee51c7a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Series", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("Series", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=mysql.TINYTEXT(),
        type_=sa.Text(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=sa.Text(length=255),
        type_=mysql.TINYTEXT(),
        existing_nullable=False,
    )
    op.drop_column("Series", "updated_at")
    op.drop_column("Series", "created_at")
    # ### end Alembic commands ###
