"""add slug column to category table

Revision ID: 6ecae55e5283
Revises: 62a07fa5d094
Create Date: 2024-03-11 17:02:57.172344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6ecae55e5283"
down_revision: Union[str, None] = "62a07fa5d094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "BillDetail",
        "quantity",
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.add_column("Category", sa.Column("slug", sa.String(length=50), nullable=True))
    op.add_column("Category", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "Category", ["slug"])
    op.drop_column("Category", "update_at")
    op.alter_column(
        "ExchangeRate",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    op.alter_column(
        "ExchangeRate",
        "currency",
        existing_type=mysql.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column("ExchangeRate", "rate", existing_type=mysql.FLOAT(), nullable=False)
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=mysql.TINYTEXT(),
        type_=sa.Text(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=sa.Text(length=255),
        type_=mysql.TINYTEXT(),
        existing_nullable=False,
    )
    op.alter_column("ExchangeRate", "rate", existing_type=mysql.FLOAT(), nullable=True)
    op.alter_column(
        "ExchangeRate",
        "currency",
        existing_type=mysql.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "ExchangeRate",
        "id",
        existing_type=sa.Uuid(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
    )
    op.add_column("Category", sa.Column("update_at", mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, "Category", type_="unique")
    op.drop_column("Category", "updated_at")
    op.drop_column("Category", "slug")
    op.alter_column(
        "BillDetail",
        "quantity",
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
