"""add slug column to series table

Revision ID: b756ee51c7a6
Revises: acbd098a84cd
Create Date: 2024-03-16 22:03:04.658052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b756ee51c7a6"
down_revision: Union[str, None] = "acbd098a84cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Series", sa.Column("slug", sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, "Series", ["slug"])
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=mysql.TINYTEXT(),
        type_=sa.Text(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserNotification",
        "content",
        existing_type=sa.Text(length=255),
        type_=mysql.TINYTEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "Series", type_="unique")
    op.drop_column("Series", "slug")
    # ### end Alembic commands ###
