from .admin import DOCUMENTATIONS as ADMIN_DOCUMENTATIONS
from .auth import DOCUMENTATIONS as AUTH_DOCUMENTATIONS
from .definition import DOCUMENTATIONS as DEFINITION_DOCUMENTATIONS
from .user import DOCUMENTATIONS as USER_DOCUMENTATIONS


__all__ = [
    "ADMIN_DOCUMENTATIONS",
    "AUTH_DOCUMENTATIONS",
    "DEFINITION_DOCUMENTATIONS",
    "USER_DOCUMENTATIONS",
]
